name: Make Doxygen Docs
on: 
  push:
    branches: [ master ]

  workflow_dispatch:
  
jobs:
    runs-on: ubuntu-latest
    steps:
 - uses: actions/checkout@v2
 - name: Documentationcreate
        uses: mattnotmitt/doxygen-action@v1.9.2
        with: 
          doxyfile-path: 'doc/Doxyfile'
 - name: upload result
        uses: actions/upload-artifact@v2
        with:
          path: doc
          name: Doxygen Documentation
 - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.
        with:
          source-directory: 'doc'
          destination-github-username: 'necheburechka'
          destination-repository-name: 'test.io'
          user-email: 2020102157@pnu.edu.ru
          target-branch: main
