name: Prog

on: 
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "prog.txt"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: echo All files exists!
        
      - name: compile
        run: |
          sudo apt install build-essential
          gcc --version
          gcc ./test/test.cpp -o test.exe
          
      - name: result
        uses: actions/upload-artifact@v2
        with:
          name: Test
          path: test.exe
      
