name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:

    runs-on:ubuntu-latest

    steps:
 - name: Checkout 
        uses: actions/checkout@v1

 - name: check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "progtest.txt"
          
 - name: File exists
        if: steps.check_files.outputs.files_exists =='true'
        # Only runs if all of the files exists
        run: echo All files exists!

